import type { PropertySummary } from './types'

/**
 * ⚠️  DEVELOPMENT DATA — NOT REAL LISTINGS.
 *
 * Seeded inventory so the interface can be built and judged against
 * realistic content before there is a database. Prices, areas and
 * localities are plausible for Kolkata; the properties themselves are
 * invented and no seller is real.
 *
 * Deliberately includes the cases that break layouts in production:
 *   • a very long title and a long society name
 *   • a ₹3.25 Cr price (the widest realistic price string)
 *   • a listing with NO photo
 *   • rent alongside sale
 *   • a missing floor / total floors
 *
 * Phase 5 replaces this file with the `property` table. Nothing above
 * lib/property/queries.ts imports it.
 */
export const DEMO_PROPERTIES: PropertySummary[] = [
  {
    id: 'demo-1',
    publicId: 'p_8f3c2a',
    slug: '3-bhk-flat-for-sale-in-new-town',
    intent: 'buy',
    propertyType: 'APARTMENT',
    title: '3 BHK flat with open balcony',
    society: 'Upohar Luxury Residences',
    localitySlug: 'new-town',
    localityName: 'New Town',
    cityName: 'Kolkata',
    price: 6250000,
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 1240,
    superArea: 1580,
    areaUnit: 'sqft',
    areaBasis: 'carpet',
    furnishing: 'SEMI_FURNISHED',
    constructionStatus: 'READY',
    floor: 7,
    totalFloors: 14,
    sellerType: 'OWNER',
    postedAt: '2026-09-17',
    photos: [{ id: 'm1', url: null, alt: '3 BHK flat in New Town, Kolkata' }],
  },
  {
    id: 'demo-2',
    publicId: 'p_2b91de',
    slug: '2-bhk-flat-for-rent-in-salt-lake-sector-v',
    intent: 'rent',
    propertyType: 'APARTMENT',
    title: '2 BHK near the IT corridor',
    society: 'Sector V Residency',
    localitySlug: 'salt-lake',
    localityName: 'Salt Lake',
    cityName: 'Kolkata',
    price: 22000,
    bedrooms: 2,
    bathrooms: 2,
    carpetArea: 940,
    areaUnit: 'sqft',
    areaBasis: 'carpet',
    furnishing: 'FURNISHED',
    constructionStatus: 'READY',
    floor: 4,
    totalFloors: 9,
    sellerType: 'AGENT',
    sellerName: 'Basu Properties',
    postedAt: '2026-09-19',
    photos: [{ id: 'm2', url: null, alt: '2 BHK flat in Salt Lake, Kolkata' }],
  },
  {
    id: 'demo-3',
    publicId: 'p_74aa01',
    slug: '4-bhk-apartment-for-sale-in-ballygunge',
    intent: 'buy',
    propertyType: 'APARTMENT',
    // Long title on purpose — cards must clamp rather than overflow.
    title: 'Spacious 4 BHK south-facing apartment with two covered parking bays and a servant room',
    society: 'Ballygunge Park Court Residency Phase II',
    localitySlug: 'ballygunge',
    localityName: 'Ballygunge',
    cityName: 'Kolkata',
    price: 32500000,
    bedrooms: 4,
    bathrooms: 4,
    carpetArea: 2340,
    superArea: 2980,
    areaUnit: 'sqft',
    areaBasis: 'carpet',
    furnishing: 'UNFURNISHED',
    constructionStatus: 'READY',
    floor: 3,
    totalFloors: 6,
    sellerType: 'AGENT',
    sellerName: 'Chatterjee Estates',
    postedAt: '2026-09-10',
    photos: [{ id: 'm3', url: null, alt: '4 BHK apartment in Ballygunge, Kolkata' }],
    isPriceReduced: true,
  },
  {
    id: 'demo-4',
    publicId: 'p_5c30b7',
    slug: '2-bhk-flat-for-sale-in-behala',
    intent: 'buy',
    propertyType: 'BUILDER_FLOOR',
    title: '2 BHK builder floor near the metro',
    localitySlug: 'behala',
    localityName: 'Behala',
    cityName: 'Kolkata',
    price: 3200000,
    bedrooms: 2,
    bathrooms: 2,
    carpetArea: 760,
    areaUnit: 'sqft',
    areaBasis: 'carpet',
    furnishing: 'UNFURNISHED',
    constructionStatus: 'READY',
    sellerType: 'OWNER',
    postedAt: '2026-09-08',
    // No photo at all — the empty-media path must look deliberate.
    photos: [],
  },
  {
    id: 'demo-5',
    publicId: 'p_9d4e6f',
    slug: '3-bhk-flat-for-rent-in-em-bypass',
    intent: 'rent',
    propertyType: 'APARTMENT',
    title: '3 BHK with balcony overlooking the lake',
    society: 'Bypass Greens',
    localitySlug: 'em-bypass',
    localityName: 'E M Bypass',
    cityName: 'Kolkata',
    price: 45000,
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 1460,
    areaUnit: 'sqft',
    areaBasis: 'carpet',
    furnishing: 'SEMI_FURNISHED',
    constructionStatus: 'READY',
    floor: 11,
    totalFloors: 18,
    sellerType: 'OWNER',
    postedAt: '2026-09-12',
    photos: [{ id: 'm5', url: null, alt: '3 BHK flat on E M Bypass, Kolkata' }],
  },
  {
    id: 'demo-6',
    publicId: 'p_1a77c3',
    slug: '3-bhk-flat-for-sale-in-rajarhat',
    intent: 'buy',
    propertyType: 'APARTMENT',
    title: '3 BHK in a gated complex',
    society: 'Chinar Park Heights',
    localitySlug: 'rajarhat',
    localityName: 'Rajarhat',
    cityName: 'Kolkata',
    price: 8400000,
    bedrooms: 3,
    bathrooms: 2,
    carpetArea: 1310,
    superArea: 1690,
    areaUnit: 'sqft',
    areaBasis: 'carpet',
    furnishing: 'UNFURNISHED',
    constructionStatus: 'UNDER_CONSTRUCTION',
    floor: 9,
    totalFloors: 16,
    sellerType: 'BUILDER',
    sellerName: 'Greenfield Developers',
    postedAt: '2026-09-11',
    photos: [{ id: 'm6', url: null, alt: '3 BHK flat in Rajarhat, Kolkata' }],
  },
  {
    id: 'demo-7',
    publicId: 'p_63b8e2',
    slug: '1-bhk-studio-for-rent-in-tollygunge',
    intent: 'rent',
    propertyType: 'STUDIO',
    title: 'Compact studio close to the metro',
    localitySlug: 'tollygunge',
    localityName: 'Tollygunge',
    cityName: 'Kolkata',
    price: 11500,
    bedrooms: 1,
    bathrooms: 1,
    carpetArea: 410,
    areaUnit: 'sqft',
    areaBasis: 'carpet',
    furnishing: 'SEMI_FURNISHED',
    constructionStatus: 'READY',
    floor: 2,
    totalFloors: 4,
    sellerType: 'OWNER',
    postedAt: '2026-09-06',
    photos: [{ id: 'm7', url: null, alt: 'Studio apartment in Tollygunge, Kolkata' }],
  },
  {
    id: 'demo-8',
    publicId: 'p_4e02fa',
    slug: '3-bhk-independent-house-for-sale-in-garia',
    intent: 'buy',
    propertyType: 'INDEPENDENT_HOUSE',
    title: '3 BHK independent house with terrace',
    localitySlug: 'garia',
    localityName: 'Garia',
    cityName: 'Kolkata',
    price: 7100000,
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 1520,
    areaUnit: 'sqft',
    areaBasis: 'carpet',
    furnishing: 'UNFURNISHED',
    constructionStatus: 'READY',
    sellerType: 'OWNER',
    postedAt: '2026-09-03',
    photos: [{ id: 'm8', url: null, alt: 'Independent house in Garia, Kolkata' }],
  },
]
